In [2]:
import os

# Caminho para a pasta de dados
data_path = 'dados/' # Como o notebook está na raiz do projeto, o caminho relativo deve funcionar

# Listar os arquivos na pasta de dados
try:
    file_list = os.listdir(data_path)
    print("Arquivos encontrados na pasta 'dados':")
    for file_name in file_list:
        if file_name.endswith('.csv'): # Filtrar apenas arquivos CSV
            print(f"- {file_name}")
except FileNotFoundError:
    print(f"Erro: A pasta '{data_path}' não foi encontrada. Verifique o caminho.")

Arquivos encontrados na pasta 'dados':
- olist_customers_dataset.csv
- olist_geolocation_dataset.csv
- olist_orders_dataset.csv
- olist_order_items_dataset.csv
- olist_order_payments_dataset.csv
- olist_order_reviews_dataset.csv
- olist_products_dataset.csv
- olist_sellers_dataset.csv
- product_category_name_translation.csv

In [3]:
import pandas as pd
import os # Já importamos antes, mas é bom ter aqui caso esta célula seja executada isoladamente.

# Caminho base para os dados
data_path = 'dados/'

In [4]:
# Carregar o dataset de clientes
customers_df = pd.read_csv(os.path.join(data_path, 'olist_customers_dataset.csv'))

# Exibir as primeiras 5 linhas
print("olist_customers_dataset.csv - Primeiras 5 linhas:")
print(customers_df.head())
print("\n--------------------------------------------------\n")

# Exibir informações sobre o DataFrame (tipos de dados, valores não nulos)
print("olist_customers_dataset.csv - Informações:")
customers_df.info()
print("\n--------------------------------------------------\n")

# Exibir o número de linhas e colunas
print(f"olist_customers_dataset.csv - Formato (linhas, colunas): {customers_df.shape}")
print("\n--------------------------------------------------\n")

# Exibir estatísticas descritivas (para colunas numéricas, se houver)
print("olist_customers_dataset.csv - Estatísticas Descritivas:")
print(customers_df.describe(include='all')) # include='all' para incluir colunas não numéricas também

olist_customers_dataset.csv - Primeiras 5 linhas:
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

--------------------------------------------------

olist_customers_dataset.csv - Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

--------------------------------------------------

olist_customers_dataset.csv - Formato (linhas, colunas): (99441, 5)

--------------------------------------------------

olist_customers_dataset.csv - Estatísticas Descritivas:
                             customer_id                customer_unique_id  \
count                              99441                             99441
unique                             99441                             96096
top     274fa6071e5e17fe303b9748641082c8  8d50f5eadf50201ccdcedfb9e2ac8455
freq                                   1                                17
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        customer_zip_code_prefix customer_city customer_state
count               99441.000000         99441          99441
unique                       NaN          4119             27
top                          NaN     sao paulo             SP
freq                         NaN         15540          41746
mean                35137.474583           NaN            NaN
std                 29797.938996           NaN            NaN
min                  1003.000000           NaN            NaN
25%                 11347.000000           NaN            NaN
50%                 24416.000000           NaN            NaN
75%                 58900.000000           NaN            NaN
max                 99990.000000           NaN            NaN

In [5]:
# 2. Tabela de Geolocalização (olist_geolocation_dataset.csv)

# Carregar o dataset de geolocalização
geolocation_df = pd.read_csv(os.path.join(data_path, 'olist_geolocation_dataset.csv'))

# Exibir as primeiras 5 linhas
print("olist_geolocation_dataset.csv - Primeiras 5 linhas:")
print(geolocation_df.head())
print("\n--------------------------------------------------\n")

# Exibir informações sobre o DataFrame
print("olist_geolocation_dataset.csv - Informações:")
geolocation_df.info()
print("\n--------------------------------------------------\n")

# Exibir o número de linhas e colunas
print(f"olist_geolocation_dataset.csv - Formato (linhas, colunas): {geolocation_df.shape}")
print("\n--------------------------------------------------\n")

# Exibir estatísticas descritivas
print("olist_geolocation_dataset.csv - Estatísticas Descritivas:")
print(geolocation_df.describe(include='all'))
print("\n--------------------------------------------------\n")

# Verificar a quantidade de prefixos de CEP únicos
print(f"Número de prefixos de CEP únicos (geolocation_zip_code_prefix): {geolocation_df['geolocation_zip_code_prefix'].nunique()}")

olist_geolocation_dataset.csv - Primeiras 5 linhas:
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP

--------------------------------------------------

olist_geolocation_dataset.csv - Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

--------------------------------------------------

olist_geolocation_dataset.csv - Formato (linhas, colunas): (1000163, 5)

--------------------------------------------------

olist_geolocation_dataset.csv - Estatísticas Descritivas:
        geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
count                  1.000163e+06     1.000163e+06     1.000163e+06
unique                          NaN              NaN              NaN
top                             NaN              NaN              NaN
freq                            NaN              NaN              NaN
mean                   3.657417e+04    -2.117615e+01    -4.639054e+01
std                    3.054934e+04     5.715866e+00     4.269748e+00
min                    1.001000e+03    -3.660537e+01    -1.014668e+02
25%                    1.107500e+04    -2.360355e+01    -4.857317e+01
50%                    2.653000e+04    -2.291938e+01    -4.663788e+01
75%                    6.350400e+04    -1.997962e+01    -4.376771e+01
max                    9.999000e+04     4.506593e+01     1.211054e+02

       geolocation_city geolocation_state
count           1000163           1000163
unique             8011                27
top           sao paulo                SP
freq             135800            404268
mean                NaN               NaN
std                 NaN               NaN
min                 NaN               NaN
25%                 NaN               NaN
50%                 NaN               NaN
75%                 NaN               NaN
max                 NaN               NaN

--------------------------------------------------

Número de prefixos de CEP únicos (geolocation_zip_code_prefix): 19015

In [6]:
# 3. Tabela de Pedidos (olist_orders_dataset.csv)

# Carregar o dataset de pedidos
orders_df = pd.read_csv(os.path.join(data_path, 'olist_orders_dataset.csv'))

# Exibir as primeiras 5 linhas
print("olist_orders_dataset.csv - Primeiras 5 linhas:")
print(orders_df.head())
print("\n--------------------------------------------------\n")

# Exibir informações sobre o DataFrame
print("olist_orders_dataset.csv - Informações:")
orders_df.info()
print("\n--------------------------------------------------\n")

# Exibir o número de linhas e colunas
print(f"olist_orders_dataset.csv - Formato (linhas, colunas): {orders_df.shape}")
print("\n--------------------------------------------------\n")

# Exibir estatísticas descritivas, incluindo colunas de data/hora como object inicialmente
print("olist_orders_dataset.csv - Estatísticas Descritivas:")
print(orders_df.describe(include='all'))
print("\n--------------------------------------------------\n")

# Verificar os valores únicos da coluna 'order_status'
print("Valores únicos em 'order_status':")
print(orders_df['order_status'].value_counts())

olist_orders_dataset.csv - Primeiras 5 linhas:
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

--------------------------------------------------

olist_orders_dataset.csv - Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

--------------------------------------------------

olist_orders_dataset.csv - Formato (linhas, colunas): (99441, 8)

--------------------------------------------------

olist_orders_dataset.csv - Estatísticas Descritivas:
                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24
freq                                   1                                 1

       order_status order_purchase_timestamp    order_approved_at  \
count         99441                    99441                99281
unique            8                    98875                90733
top       delivered      2018-08-02 12:05:26  2018-02-27 04:31:10
freq          96478                        3                    9

       order_delivered_carrier_date order_delivered_customer_date  \
count                         97658                         96476
unique                        81018                         95664
top             2018-05-09 15:48:00           2018-05-08 19:36:48
freq                             47                             3

       order_estimated_delivery_date
count                          99441
unique                           459
top              2017-12-20 00:00:00
freq                             522

--------------------------------------------------

Valores únicos em 'order_status':
order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [7]:
# 4. Tabela de Itens do Pedido (olist_order_items_dataset.csv)

# Carregar o dataset de itens do pedido
order_items_df = pd.read_csv(os.path.join(data_path, 'olist_order_items_dataset.csv'))

# Exibir as primeiras 5 linhas
print("olist_order_items_dataset.csv - Primeiras 5 linhas:")
print(order_items_df.head())
print("\n--------------------------------------------------\n")

# Exibir informações sobre o DataFrame
print("olist_order_items_dataset.csv - Informações:")
order_items_df.info()
print("\n--------------------------------------------------\n")

# Exibir o número de linhas e colunas
print(f"olist_order_items_dataset.csv - Formato (linhas, colunas): {order_items_df.shape}")
print("\n--------------------------------------------------\n")

# Exibir estatísticas descritivas
print("olist_order_items_dataset.csv - Estatísticas Descritivas:")
print(order_items_df.describe(include='all'))
print("\n--------------------------------------------------\n")

# Verificar a quantidade de order_id únicos e order_item_id
print(f"Número de order_id únicos: {order_items_df['order_id'].nunique()}")
print(f"Valores únicos e contagem para 'order_item_id':")
print(order_items_df['order_item_id'].value_counts().sort_index())

olist_order_items_dataset.csv - Primeiras 5 linhas:
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14

--------------------------------------------------

olist_order_items_dataset.csv - Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

--------------------------------------------------

olist_order_items_dataset.csv - Formato (linhas, colunas): (112650, 7)

--------------------------------------------------

olist_order_items_dataset.csv - Estatísticas Descritivas:
                                order_id  order_item_id  \
count                             112650  112650.000000
unique                             98666            NaN
top     8272b63d03f5f79c56e9e4120aec44ef            NaN
freq                                  21            NaN
mean                                 NaN       1.197834
std                                  NaN       0.705124
min                                  NaN       1.000000
25%                                  NaN       1.000000
50%                                  NaN       1.000000
75%                                  NaN       1.000000
max                                  NaN      21.000000

                              product_id                         seller_id  \
count                             112650                            112650
unique                             32951                              3095
top     aca2eb7d00ea1a7b8ebd4e68314663af  6560211a19b47992c3666cc44a7e94c0
freq                                 527                              2033
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        shipping_limit_date          price  freight_value
count                112650  112650.000000  112650.000000
unique                93318            NaN            NaN
top     2018-03-01 02:50:48            NaN            NaN
freq                     21            NaN            NaN
mean                    NaN     120.653739      19.990320
std                     NaN     183.633928      15.806405
min                     NaN       0.850000       0.000000
25%                     NaN      39.900000      13.080000
50%                     NaN      74.990000      16.260000
75%                     NaN     134.900000      21.150000
max                     NaN    6735.000000     409.680000

--------------------------------------------------

Número de order_id únicos: 98666
Valores únicos e contagem para 'order_item_id':
order_item_id
1     98666
2      9803
3      2287
4       965
5       460
6       256
7        58
8        36
9        28
10       25
11       17
12       13
13        8
14        7
15        5
16        3
17        3
18        3
19        3
20        3
21        1
Name: count, dtype: int64

In [8]:
# 5. Tabela de Pagamentos do Pedido (olist_order_payments_dataset.csv)

# Carregar o dataset de pagamentos
order_payments_df = pd.read_csv(os.path.join(data_path, 'olist_order_payments_dataset.csv'))

# Exibir as primeiras 5 linhas
print("olist_order_payments_dataset.csv - Primeiras 5 linhas:")
print(order_payments_df.head())
print("\n--------------------------------------------------\n")

# Exibir informações sobre o DataFrame
print("olist_order_payments_dataset.csv - Informações:")
order_payments_df.info()
print("\n--------------------------------------------------\n")

# Exibir o número de linhas e colunas
print(f"olist_order_payments_dataset.csv - Formato (linhas, colunas): {order_payments_df.shape}")
print("\n--------------------------------------------------\n")

# Exibir estatísticas descritivas
print("olist_order_payments_dataset.csv - Estatísticas Descritivas:")
print(order_payments_df.describe(include='all'))
print("\n--------------------------------------------------\n")

# Verificar os valores únicos da coluna 'payment_type'
print("Valores únicos em 'payment_type':")
print(order_payments_df['payment_type'].value_counts())
print("\n--------------------------------------------------\n")

# Verificar os valores únicos da coluna 'payment_sequential'
# Isso indica se um pedido teve múltiplas formas de pagamento ou múltiplos pagamentos
print("Valores únicos em 'payment_sequential':")
print(order_payments_df['payment_sequential'].value_counts().sort_index())

olist_order_payments_dataset.csv - Primeiras 5 linhas:
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45

--------------------------------------------------

olist_order_payments_dataset.csv - Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

--------------------------------------------------

olist_order_payments_dataset.csv - Formato (linhas, colunas): (103886, 5)

--------------------------------------------------

olist_order_payments_dataset.csv - Estatísticas Descritivas:
                                order_id  payment_sequential payment_type  \
count                             103886       103886.000000       103886
unique                             99440                 NaN            5
top     fa65dad1b0e818e3ccc5cb0e39231352                 NaN  credit_card
freq                                  29                 NaN        76795
mean                                 NaN            1.092679          NaN
std                                  NaN            0.706584          NaN
min                                  NaN            1.000000          NaN
25%                                  NaN            1.000000          NaN
50%                                  NaN            1.000000          NaN
75%                                  NaN            1.000000          NaN
max                                  NaN           29.000000          NaN

        payment_installments  payment_value
count          103886.000000  103886.000000
unique                   NaN            NaN
top                      NaN            NaN
freq                     NaN            NaN
mean                2.853349     154.100380
std                 2.687051     217.494064
min                 0.000000       0.000000
25%                 1.000000      56.790000
50%                 1.000000     100.000000
75%                 4.000000     171.837500
max                24.000000   13664.080000

--------------------------------------------------

Valores únicos em 'payment_type':
payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

--------------------------------------------------

Valores únicos em 'payment_sequential':
payment_sequential
1     99360
2      3039
3       581
4       278
5       170
6       118
7        82
8        54
9        43
10       34
11       29
12       21
13       13
14       10
15        8
16        6
17        6
18        6
19        6
20        4
21        4
22        3
23        2
24        2
25        2
26        2
27        1
28        1
29        1
Name: count, dtype: int64

In [9]:
# 6. Tabela de Avaliações do Pedido (olist_order_reviews_dataset.csv)

# Carregar o dataset de avaliações
order_reviews_df = pd.read_csv(os.path.join(data_path, 'olist_order_reviews_dataset.csv'))

# Exibir as primeiras 5 linhas
print("olist_order_reviews_dataset.csv - Primeiras 5 linhas:")
print(order_reviews_df.head())
print("\n--------------------------------------------------\n")

# Exibir informações sobre o DataFrame
print("olist_order_reviews_dataset.csv - Informações:")
order_reviews_df.info()
print("\n--------------------------------------------------\n")

# Exibir o número de linhas e colunas
print(f"olist_order_reviews_dataset.csv - Formato (linhas, colunas): {order_reviews_df.shape}")
print("\n--------------------------------------------------\n")

# Exibir estatísticas descritivas
print("olist_order_reviews_dataset.csv - Estatísticas Descritivas:")
print(order_reviews_df.describe(include='all'))
print("\n--------------------------------------------------\n")

# Verificar os valores únicos e contagem para 'review_score'
print("Valores únicos e contagem para 'review_score':")
print(order_reviews_df['review_score'].value_counts().sort_index())
print("\n--------------------------------------------------\n")

# Verificar a porcentagem de valores ausentes nas colunas de comentário
print("Porcentagem de valores ausentes nas colunas de comentário:")
print(f"review_comment_title: {order_reviews_df['review_comment_title'].isnull().sum() / len(order_reviews_df) * 100:.2f}%")
print(f"review_comment_message: {order_reviews_df['review_comment_message'].isnull().sum() / len(order_reviews_df) * 100:.2f}%")

olist_order_reviews_dataset.csv - Primeiras 5 linhas:
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53

--------------------------------------------------

olist_order_reviews_dataset.csv - Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

--------------------------------------------------

olist_order_reviews_dataset.csv - Formato (linhas, colunas): (99224, 7)

--------------------------------------------------

olist_order_reviews_dataset.csv - Estatísticas Descritivas:
                               review_id                          order_id  \
count                              99224                             99224
unique                             98410                             98673
top     08528f70f579f0c830189efc523d2182  df56136b8031ecd28e200bb18e6ddb2e
freq                                   3                                 3
mean                                 NaN                               NaN
std                                  NaN                               NaN
min                                  NaN                               NaN
25%                                  NaN                               NaN
50%                                  NaN                               NaN
75%                                  NaN                               NaN
max                                  NaN                               NaN

        review_score review_comment_title review_comment_message  \
count   99224.000000                11568                  40977
unique           NaN                 4527                  36159
top              NaN            Recomendo              Muito bom
freq             NaN                  423                    230
mean        4.086421                  NaN                    NaN
std         1.347579                  NaN                    NaN
min         1.000000                  NaN                    NaN
25%         4.000000                  NaN                    NaN
50%         5.000000                  NaN                    NaN
75%         5.000000                  NaN                    NaN
max         5.000000                  NaN                    NaN

       review_creation_date review_answer_timestamp
count                 99224                   99224
unique                  636                   98248
top     2017-12-19 00:00:00     2017-06-15 23:21:05
freq                    463                       4
mean                    NaN                     NaN
std                     NaN                     NaN
min                     NaN                     NaN
25%                     NaN                     NaN
50%                     NaN                     NaN
75%                     NaN                     NaN
max                     NaN                     NaN

--------------------------------------------------

Valores únicos e contagem para 'review_score':
review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

--------------------------------------------------

Porcentagem de valores ausentes nas colunas de comentário:
review_comment_title: 88.34%
review_comment_message: 58.70%

In [10]:
# 7. Tabela de Produtos (olist_products_dataset.csv)

# Carregar o dataset de produtos
products_df = pd.read_csv(os.path.join(data_path, 'olist_products_dataset.csv'))

# Exibir as primeiras 5 linhas
print("olist_products_dataset.csv - Primeiras 5 linhas:")
print(products_df.head())
print("\n--------------------------------------------------\n")

# Exibir informações sobre o DataFrame
print("olist_products_dataset.csv - Informações:")
products_df.info()
print("\n--------------------------------------------------\n")

# Exibir o número de linhas e colunas
print(f"olist_products_dataset.csv - Formato (linhas, colunas): {products_df.shape}")
print("\n--------------------------------------------------\n")

# Exibir estatísticas descritivas
print("olist_products_dataset.csv - Estatísticas Descritivas:")
print(products_df.describe(include='all'))
print("\n--------------------------------------------------\n")

# Verificar a quantidade de categorias de produtos únicas
# e a contagem de produtos por categoria (Top 10)
if 'product_category_name' in products_df.columns:
    print(f"Número de categorias de produto únicas: {products_df['product_category_name'].nunique()}")
    print("\nTop 10 categorias de produto mais frequentes:")
    print(products_df['product_category_name'].value_counts().nlargest(10))
else:
    print("A coluna 'product_category_name' não foi encontrada.")

olist_products_dataset.csv - Primeiras 5 linhas:
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

--------------------------------------------------

olist_products_dataset.csv - Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

--------------------------------------------------

olist_products_dataset.csv - Formato (linhas, colunas): (32951, 9)

--------------------------------------------------

olist_products_dataset.csv - Estatísticas Descritivas:
                              product_id product_category_name  \
count                              32951                 32341
unique                             32951                    73
top     106392145fca363410d287a815be6de4       cama_mesa_banho
freq                                   1                  3029
mean                                 NaN                   NaN
std                                  NaN                   NaN
min                                  NaN                   NaN
25%                                  NaN                   NaN
50%                                  NaN                   NaN
75%                                  NaN                   NaN
max                                  NaN                   NaN

        product_name_lenght  product_description_lenght  product_photos_qty  \
count          32341.000000                32341.000000        32341.000000
unique                  NaN                         NaN                 NaN
top                     NaN                         NaN                 NaN
freq                    NaN                         NaN                 NaN
mean              48.476949                  771.495285            2.188986
std               10.245741                  635.115225            1.736766
min                5.000000                    4.000000            1.000000
25%               42.000000                  339.000000            1.000000
50%               51.000000                  595.000000            1.000000
75%               57.000000                  972.000000            3.000000
max               76.000000                 3992.000000           20.000000

        product_weight_g  product_length_cm  product_height_cm  \
count       32949.000000       32949.000000       32949.000000
unique               NaN                NaN                NaN
top                  NaN                NaN                NaN
freq                 NaN                NaN                NaN
mean         2276.472488          30.815078          16.937661
std          4282.038731          16.914458          13.637554
min             0.000000           7.000000           2.000000
25%           300.000000          18.000000           8.000000
50%           700.000000          25.000000          13.000000
75%          1900.000000          38.000000          21.000000
max         40425.000000         105.000000         105.000000

        product_width_cm
count       32949.000000
unique               NaN
top                  NaN
freq                 NaN
mean           23.196728
std            12.079047
min             6.000000
25%            15.000000
50%            20.000000
75%            30.000000
max           118.000000

--------------------------------------------------

Número de categorias de produto únicas: 73

Top 10 categorias de produto mais frequentes:
product_category_name
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

In [11]:
# 8. Tabela de Vendedores (olist_sellers_dataset.csv)

# Carregar o dataset de vendedores
sellers_df = pd.read_csv(os.path.join(data_path, 'olist_sellers_dataset.csv'))

# Exibir as primeiras 5 linhas
print("olist_sellers_dataset.csv - Primeiras 5 linhas:")
print(sellers_df.head())
print("\n--------------------------------------------------\n")

# Exibir informações sobre o DataFrame
print("olist_sellers_dataset.csv - Informações:")
sellers_df.info()
print("\n--------------------------------------------------\n")

# Exibir o número de linhas e colunas
print(f"olist_sellers_dataset.csv - Formato (linhas, colunas): {sellers_df.shape}")
print("\n--------------------------------------------------\n")

# Exibir estatísticas descritivas
print("olist_sellers_dataset.csv - Estatísticas Descritivas:")
print(sellers_df.describe(include='all'))
print("\n--------------------------------------------------\n")

# Verificar a quantidade de cidades e estados únicos dos vendedores
if 'seller_city' in sellers_df.columns and 'seller_state' in sellers_df.columns:
    print(f"Número de cidades únicas de vendedores: {sellers_df['seller_city'].nunique()}")
    print(f"Número de estados únicos de vendedores: {sellers_df['seller_state'].nunique()}")
    print("\nTop 10 cidades de vendedores mais frequentes:")
    print(sellers_df['seller_city'].value_counts().nlargest(10))
    print("\nTop 10 estados de vendedores mais frequentes:")
    print(sellers_df['seller_state'].value_counts().nlargest(10))
else:
    print("Colunas 'seller_city' ou 'seller_state' não encontradas.")

olist_sellers_dataset.csv - Primeiras 5 linhas:
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP

--------------------------------------------------

olist_sellers_dataset.csv - Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

--------------------------------------------------

olist_sellers_dataset.csv - Formato (linhas, colunas): (3095, 4)

--------------------------------------------------

olist_sellers_dataset.csv - Estatísticas Descritivas:
                               seller_id  seller_zip_code_prefix seller_city  \
count                               3095             3095.000000        3095
unique                              3095                     NaN         611
top     9e25199f6ef7e7c347120ff175652c3b                     NaN   sao paulo
freq                                   1                     NaN         694
mean                                 NaN            32291.059451         NaN
std                                  NaN            32713.453830         NaN
min                                  NaN             1001.000000         NaN
25%                                  NaN             7093.500000         NaN
50%                                  NaN            14940.000000         NaN
75%                                  NaN            64552.500000         NaN
max                                  NaN            99730.000000         NaN

       seller_state
count          3095
unique           23
top              SP
freq           1849
mean            NaN
std             NaN
min             NaN
25%             NaN
50%             NaN
75%             NaN
max             NaN

--------------------------------------------------

Número de cidades únicas de vendedores: 611
Número de estados únicos de vendedores: 23

Top 10 cidades de vendedores mais frequentes:
seller_city
sao paulo         694
curitiba          127
rio de janeiro     96
belo horizonte     68
ribeirao preto     52
guarulhos          50
ibitinga           49
santo andre        45
campinas           41
maringa            40
Name: count, dtype: int64

Top 10 estados de vendedores mais frequentes:
seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
Name: count, dtype: int64

In [12]:
# 9. Tabela de Tradução de Nomes de Categoria de Produto (product_category_name_translation.csv)

# Carregar o dataset de tradução de categorias
category_translation_df = pd.read_csv(os.path.join(data_path, 'product_category_name_translation.csv'))

# Exibir as primeiras 5 linhas
print("product_category_name_translation.csv - Primeiras 5 linhas:")
print(category_translation_df.head())
print("\n--------------------------------------------------\n")

# Exibir informações sobre o DataFrame
print("product_category_name_translation.csv - Informações:")
category_translation_df.info()
print("\n--------------------------------------------------\n")

# Exibir o número de linhas e colunas
print(f"product_category_name_translation.csv - Formato (linhas, colunas): {category_translation_df.shape}")
print("\n--------------------------------------------------\n")

# Exibir estatísticas descritivas (embora aqui seja mais sobre o mapeamento)
print("product_category_name_translation.csv - Estatísticas Descritivas:")
print(category_translation_df.describe(include='all'))
print("\n--------------------------------------------------\n")

# Verificar se há nomes de categoria únicos em português e inglês
print(f"Número de 'product_category_name' (PT) únicos: {category_translation_df['product_category_name'].nunique()}")
print(f"Número de 'product_category_name_english' (EN) únicos: {category_translation_df['product_category_name_english'].nunique()}")

product_category_name_translation.csv - Primeiras 5 linhas:
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

--------------------------------------------------

product_category_name_translation.csv - Informações:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

--------------------------------------------------

product_category_name_translation.csv - Formato (linhas, colunas): (71, 2)

--------------------------------------------------

product_category_name_translation.csv - Estatísticas Descritivas:
       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

--------------------------------------------------

Número de 'product_category_name' (PT) únicos: 71
Número de 'product_category_name_english' (EN) únicos: 71